//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worker.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBWorkerEntities : DbContext
    {
        public DBWorkerEntities()
            : base("name=DBWorkerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blood> Blood { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<DrivingLiense> DrivingLiense { get; set; }
        public virtual DbSet<Hobby> Hobby { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<TelephoneCode> TelephoneCode { get; set; }
    }
}
