//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worker.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int WorkerId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int CityId { get; set; }
        public string Address { get; set; }
        public int BloodId { get; set; }
        public int DrivingId { get; set; }
        public string Email { get; set; }
        public int TelephoneCodeId { get; set; }
        public string Telephone { get; set; }
        public int HobbyId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Blood Blood { get; set; }
        public virtual City City { get; set; }
        public virtual DrivingLiense DrivingLiense { get; set; }
        public virtual Hobby Hobby { get; set; }
        public virtual TelephoneCode TelephoneCode { get; set; }
    }
}
